### ISSUE TITLE
A simple calculator

### ISSUE THREAD

**Issue by byCedric** [mdavis1982/eve#22]
### Aim

A small and simple calculator.
### Syntax

The syntax could be simple like this `calc {formula}`.

```
@eve calc 56048 / 250
@eve calc 1 + 1
@eve calc (60 / 2) * 10
```
### Development Requirements

Explain in a list what needs to be done to get the command working:
- Listen for the `calc` command
- Parse out the mathematical formula
- Evaluate the formula
- Return a message to the user with the following information: `@user {formula} = {outcome}`
### Nice To Have

We could, in the future, try to parse a real physics formula. But that is future talk.

**Comment by byCedric** [comment]
I can pick this up this evening

**Comment by byCedric** [comment]
Ok, so here is my progress. I put a little effort into finding out if we can easily evaluate formulas _without_ the need of a library. Unfortunately, if we do this we have to make it evil (use `eval`). Because of this I went on the quest to find a good mathematical expression library, so far I've come up with this.
- [Aboyadzhiev PHP Math Parser](https://github.com/aboyadzhiev/php-math-parser)
- [Hoa Math](https://github.com/hoaproject/Math)
- [Mossadal Math Parser](https://github.com/mossadal/math-parser)
- [NXP Math Executor](https://github.com/NeonXP/MathExecutor)
- [Symfony Expression Language](https://github.com/symfony/expression-language)
- [Webit Eval Math](https://github.com/dbojdo/eval-math)

I also compared them against each other:

| criteria | Aboyadzhiev | Hoa | Mossadal | NXP | Symfony | Webit |
| --- | --- | --- | --- | --- | --- | --- |
| latest version | dev-master | 1.16.08.29 | 1.2.3 | 0.1 | 3.1.5 | 1.0.1 |
| license | MIT | BSD-3-Clause | LGPL-3.0 | MIT | MIT | BSD-3-Clause |
| has (unit) testing | _barely_ | **yes** | **yes** | _barely_ | **yes** | _barely_ |
| can evaluate algebra | _no_ | **yes** | **yes** | **yes** | _kinda_ | _no_ |
| average ms for `1 + 1` | `0.00018ms` | `0.01379ms` | `0.00100ms` | `0.00030ms` | `0.00035ms` | `0.00017ms` |
| average ms for `x*3 + x^(2 + 1) + (y - 3/3)` (`x=9`, `y=3`) | _failed_ | `0.02375ms` | `0.00557ms` | `0.00095ms` _wrong value_ | `0.00099ms` _wrong value_ | `0.00061ms` |

> Tested on a MacBook Pro (Retina, 13-inch, Early 2015), macOS Sierra, 2.7GHz i5, 16GB 1867 DDR3 in terminal with with some programs open.

My personal favorites are Mossadal and Webit.

**Comment by byCedric** [comment]
Also I would like to update the syntax. Since some libraries can even evaluate algebra we can update the syntax with this: `@eve calc {expression} {--variable=value}`. This means that we can do the following:

```
@eve calc 1 + 1
@eve calc 1 + x --x=9
@eve calc x*sin(x)*cos(x)^2+y --x=5 --y=9
```

> Again, this syntax is only possible when using a library which can evaluate algebra.

**Comment by byCedric** [comment]
Any thoughts?

**Comment by mdavis1982** [comment]
This is awesome! Syntax can certainly be updated.

It would be worth checking out the `refactor` branch to base this on as that should be at a point where it can be deployed soon.

Thanks!

**Comment by byCedric** [comment]
I deviated a little from the return message `{formula} = {outcome}`. Because of the added algebra support this became a little _unclear_, e.g.

| command | response |
| --- | --- |
| `calc 1 + 1` | `1 + 1 = 2` |
| `calc x*3 + x^(2 + 1) + (y - 3/3) --x=9 --y=3` | `x*3 + x^(2 + 1) + (y - 3/3) = 758 (where x=9, y=3)` |

Because of this I used the following, more expressive (and readable) syntax.

| command | response |
| --- | --- |
| `calc 1 + 1` | `1 + 1 _evaluates to_ *2*` |
| `calc x*3 + x^(2 + 1) + (y - 3/3) --x=9 --y=3` | `x*3 + x^(2 + 1) + (y - 3/3) _evaluates to_ *758* _where_ x=9, y=3` |

> Note, I've used markdown to mark the outcome bold, the formula and variables normal and the text italic`

**Comment by mdavis1982** [comment]
This is brilliant.

In the second calc command above, how does it know what to set `x` and `y` to in the response?

**Comment by byCedric** [comment]
You have to provide it in the command. I forgot to put it in the example, my bad.
