### ISSUE TITLE
Enable multiple recipients for the slap command

### ISSUE THREAD

**Issue by Riari** [mdavis1982/eve#23]
### Aim

Make it possible to mention more than one user when issuing the slap command and have Eve respond by slapping them all at once.
### Syntax

```
@eve slap @andreaselia @dylan.dpc @darrentaytay
```
### Development Requirements

Extend the existing slap command to parse the list of users and display them as a comma-separated list in the message output. The rest of the message format can remain as-is. Example based on the above syntax:

_slaps @andreaselia, @dylan.dpc, @darrentaytay with a large wet fish 🐟_
### Nice To Have
- Use `and` instead of `,` for the last user in the list
- A limit on the number of recipients to prevent a mass slappening. In fact, that should probably be a 'must have'...

**Comment by mdavis1982** [comment]
This is now done and is live - including all of the nice to have features.
