### ISSUE TITLE
UserJoinsChannelHandler causes notification spam

### ISSUE THREAD

**Issue by sisve** [mdavis1982/eve#54]
### Aim
The current implementation of UserJoinsChannelHandler will send a message into a channel on every join, causing all members to get notifications about unread messages during otherwise idle periods when people only join/leave.

### Development Requirements
Remove UserJoinsChannelHandler from config/eve.php

**Comment by Helfull** [comment]
Would change to send private messages to the person joining

**Comment by Riari** [comment]
I think it's just an unnecessary feature really - at least in any channel other than the default. If it can somehow tell when a user joins the _server_ for the first time and DM them with a summary of the most popular channels, that would be infinitely more useful.

Otherwise, +1 for removing it :)

**Comment by mdavis1982** [comment]
This can be removed - it was actually only a test of some functionality that I want to implement.

Please submit a PR that removes it both from the config and removes the actual Handler class too.

Thanks 😄
