### ISSUE TITLE
Create a weather command

### ISSUE THREAD

**Issue by mdavis1982** [mdavis1982/eve#9]
**Commands:**

`@eve weather <place>`

**Development requirements:**
- Listen for the command `weather`.
- Parse out the strings after `weather` and search a weather API for the result
- If we have a result, return the information.
- If no result, return a message to the user to inform them of no results found.

**Nice to have:**
- Allow a 5-day or 7-day forecast
- Add icons to the result indicating weather conditions

**Comment by andreaselia** [comment]
I've already made a start on this so I'll do it

**Comment by andreaselia** [comment]
I have submitted a PR that meets the requirements, the "nice to have" will need to wait until support for attachments and/or optional arguments are supported.

**Comment by mdavis1982** [comment]
The PR that was previously accepted for this caused some unforeseen issues. It has been reverted.

**Comment by alexqhj** [comment]
I'll take a stab at this :)

**Comment by andreaselia** [comment]
I'm happy for @ahjorth to take over on this command.
